import os

# Set environment variable for Hugging Face token
os.environ["HUGGINGFACE_TOKEN"] = "your_token_here"


["HUGGINGFACE_TOKEN"]["key"] = "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"


from dotenv import load_dotenv

load_dotenv()
